---
apiVersion: helm.integrations.flux.weave.works/v1alpha2
kind: FluxHelmRelease
metadata:
  name: podinfo-adm
  namespace: adm
  annotations:
    flux.weave.works/automated: "false"
    flux.weave.works/tag.chart-image: semver:~1.2
spec:
  chartGitPath: podinfo-v1
  releaseName: podinfo-adm
  values:

    image:
      repository: quay.io/stefanprodan/podinfo
      tag: 1.2.0
      pullPolicy: IfNotPresent

    service:
      type: LoadBalancer
