---
apiVersion: helm.integrations.flux.weave.works/v1alpha2
kind: FluxHelmRelease
metadata:
  name: podinfo-dev
  namespace: dev
  labels:
    chart: podinfo
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.podinfo: glob:dev-*
spec:
  chartGitPath: podinfo
  releaseName: podinfo-dev
  values:
    image: stefanprodan/podinfo:dev-2aywpdbq
    replicaCount: 1
    hpa:
      enabled: false
