---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: weave-flux-helm-operator
  namespace: weave
  labels:
    app: weave-flux-helm-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weave-flux-helm-operator
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: weave-flux-helm-operator
    spec:
      serviceAccount: weave-agent
      volumes:
      - name: git-key
        secret:
          secretName: flux-git-deploy
      containers:
      - name: helm-operator
        image: quay.io/weaveworks/helm-operator:alpha
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: git-key
          mountPath: /etc/fluxd/ssh
        args:
        - --git-url=git@github.com:stefanprodan/helm-flux-demo
        - --git-branch=master
        - --git-charts-path=charts
