---
apiVersion: helm.integrations.flux.weave.works/v1alpha2
kind: FluxHelmRelease
metadata:
  name: podinfo-prod
  namespace: prod
  labels:
    chart: podinfo
spec:
  chartGitPath: podinfo
  releaseName: podinfo-dev
  values:
    image: quay.io/stefanprodan/podinfo:0.5.0
    replicaCount: 1
    hpa:
      enabled: false
