---
apiVersion: helm.integrations.flux.weave.works/v1alpha
kind: FluxHelmRelease
metadata:
  name: frontend
  namespace: default
  labels:
    chart: podinfo
spec:
  chartGitPath: podinfo
  values:
    - name: image.repository
      value: stefanprodan/podinfo
    - name: image.tag
      value: 0.0.6
