---
apiVersion: helm.integrations.flux.weave.works/v1alpha
kind: FluxHelmRelease
metadata:
  name: backend
  namespace: default
  labels:
    chart: podinfo
spec:
  chartGitPath: podinfo
  releaseName: backend
  values:
    replicaCount: 1
    image:
      tag: 0.2.2
